Ok2

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -42,9 +42,9 @@ jobs:
       run: terraform plan -no-color
       continue-on-error: true
 
-    - name: Terraform Plan Status 
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+   # - name: Terraform Plan Status 
+   #   if: steps.plan.outcome == 'failure'
+   #   run: exit 1
     
       
       # On push to master, build or change infrastructure according to Terraform configuration files
