exec

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -1,64 +1,59 @@
-name: "Terraform Deployment"
+name: "Terraform-Apply-Infra-Plan"
+
 on:
-  # Manual trigger
-  workflow_dispatch:
   push:
-    paths:
-      - '*/**'
-  pull_request:
-    branches: [ main ]
+    branches:
+    - main
+
 defaults:
-  run:
-    shell: bash
+ run:
+  working-directory: development  
+
 jobs:
   terraform:
-    name:   ${{matrix.runner}} - ${{ matrix.environment }}
-    runs-on: [ '${{ matrix.runner }}']
-    strategy:
-      max-parallel: 1
-      matrix:
-         include:
-           - environment: development
-             runner: ubuntu-latest
-           - environment: production
-             runner: ubuntu-18.04
-    env:
-         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-         AWS_DEFAULT_REGION: us-east-2
-    steps:
-      - uses: actions/checkout@v2
-      - uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_wrapper: false
-      - name: Terraform Init
-        id: init
-        run: |
-           rm -rf .terraform
-           terraform init -backend-config=${{ matrix.environment }}/main.tf -upgrade=true -no-color -input=false
-      - name: Terraform Plan
-        id: plan
-        run: |
-          terraform plan -input=false -var-file=${{ matrix.environment }}/variables.tf -no-color
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main'
-        id: apply
-        run: terraform apply -auto-approve -input=false -var-file=${{ matrix.environment }}/variables.tf
-      - name: Terraform destroy
-        if: github.ref == 'refs/heads/destroy'
-        id: destroy
-        run: terraform destroy -auto-approve -input=false -var-file=${{ matrix.environment }}/variables.tf
-  comment:
+    name: 'Terraform'
     runs-on: ubuntu-latest
-    needs: terraform
-    if: github.event_name == 'pull_request'
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
+      AWS_SECRET_KEY_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
+      AWS_REGION: 'us-east-2'
+
+    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+    defaults:
+      run:
+        shell: bash
+
+    # Checkout the repository to the GitHub Actions runner
     steps:
-      - uses: actions/github-script@v5
-        with:
-          script: |
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: '👋 Thanks for reporting!'
-            })
+    - name: Checkout
+      uses: actions/checkout@v2
+
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v1    
+      with:
+        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+   
+    
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      id: init 
+      run: terraform init
+
+    # Generates an execution plan for Terraform
+    - name: Terraform Plan
+      id: plan
+      if: github.event_name == 'push'
+      run: terraform plan -no-color
+      continue-on-error: true
+
+   # - name: Terraform Plan Status 
+   #   if: steps.plan.outcome == 'failure'
+   #   run: exit 1
+    
+      
+      # On push to master, build or change infrastructure according to Terraform configuration files
+      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+    - name: Terraform Apply
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      run: terraform apply -auto-approve
